### ISSUE TITLE
Add variant data

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDashboard#11]
Variant data is now available by province from CTV's [variant tracker](https://www.ctvnews.ca/health/coronavirus/tracking-variants-of-the-novel-coronavirus-in-canada-1.5296141).

**Comment by jeanpaulrsoucy** [comment]
Variant time series are also available from PHAC: see scraping code in the appendix of this report.

https://drive.google.com/file/d/1BY1lC_3YwAJVOdUbGKrDlxNHAwk0bMn4/view

It is very similar to the CTV variant tracker and also at the province level.

**Comment by kbelisar** [comment]
Since VOC data is reported after the specimen is initially confirmed as positive for COVID-19, it has been difficult to visualize variants alongside reported case numbers. Have provided several visualizations to mull over and decide on the best approach.

**Comment by kbelisar** [comment]
Latest push is more streamlined - with data information moved to the 'About' tab.

**Comment by jeanpaulrsoucy** [comment]
Note that the current code in the variants branch (cb610b2) will fail if the variant data doesn't have the same maximum date as the rest of the data (i.e., if the variant data gets updated late/not at all). We will need to add a separate max date for the variant data.
