### ISSUE TITLE
Upgrading cumulative plot function

### ISSUE THREAD

**Issue by benkcwong** [ccodwg/Covid19CanadaDashboard#16]
@benkcwong: For the per-capita plots, I'm almost wondering if we can roll up this plot with the other cumulative plot and have two options: over time (line graph) versus current (bar graph) and per-capita versus absolute. We could also use unified hover pointed out by @kbelisar to facilitate comparison on the line graphs. I'll give these a think over.

_Originally posted by @jeanpaulrsoucy in https://github.com/ccodwg/Covid19CanadaDashboard/issues/3#issuecomment-778672523_

**Comment by benkcwong** [comment]
@jeanpaulrsoucy and I discussed updating the cumulative plot function to include the time-series (line graph) and current (bar graph) for use with the vaccine distribution/administration graphs. One suggestion is to organize it like we do in the comparisons tab. Vaccines distributed and administered would be in separate rows, with 2 radio buttons for absolute/per-capita and 2 radio buttons for time-series (line) vs. current (bar).

**Comment by benkcwong** [comment]
Updated the cumulative plot function at [`8fa7a05`](https://github.com/ccodwg/Covid19CanadaDashboard/commit/8fa7a05bd27d24fba86b0b3a3e82e6202697e70e). All cumulative plots and vaccine plots were modified to show line/bar graphs by absolute/per-capita using radio buttons.

**Comment by jeanpaulrsoucy** [comment]
This is great, @benkcwong. A few notes:

- The cumulative plot title should adjust depending on whether (similar to the comparison tab)
- Hovertext seems to be missing for the plots unless you manually click on them (see main version of the vaccine gap plot to see how unified hovertext is implemented for other plots)
- Your .gitingore file seems to have reverted to the default --- please replace with the version in main to avoid merge conflicts

**Comment by jeanpaulrsoucy** [comment]
Per our discussion today, we should also switch the default to "line" and "absolute" to conform with the previous default.

**Comment by benkcwong** [comment]
Thanks JP! New commit ([916e69f](https://github.com/ccodwg/Covid19CanadaDashboard/commit/916e69ff5bf4f5d85bf57f6218c28af550f1e588)) has the adjusted titles using a new function, added unified hovertext (needed to remove the old text formatting as the text box couldn't fit all the province information), reverted the .gitignore file, and switched the default on the cumulative plot to "line" and "absolute.
