### ISSUE TITLE
Revamp 7-day average plots on overview tab

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDashboard#21]
- [x] **x-axis should be date, not days since x cumulative cases.** While this feature made sense early on, it has outlasted its usefulness and now hampers comparison rather than helping it.
- [ ] **Add per-capita toggle.** This facilitates comparisons between provinces.
- [x] **Move info/options below plot.** At the moment, it is not clear what this info is referring to until you scroll down further and see the plot.
- [x] **Condense info below plot.** The info below the plot can probably be condensed, especially if the plot is going to be simplified (date on x-axis).
- [x] **Add date slider.** Only show the most recent information by default (e.g., the last 3 months).

**Comment by benkcwong** [comment]
Added per-capita toggle to "overview-per-capita" branch ([e2c0fac](https://github.com/ccodwg/Covid19CanadaDashboard/commit/e2c0fac6f89f7520959483904fc00ee784d62090)). 
May look to tweak the placement of the radio button as it takes up quite a bit more space now with the extra row of buttons.
