### ISSUE TITLE
Increase font size and contrast of text in overview page

### ISSUE THREAD

**Issue by benkcwong** [ccodwg/Covid19CanadaDashboard#29]
It may be difficult to see the different tabs that can be opened up on overview page. It might help to increase the font of the tab panel text and also add contrast to make it obvious they are clickable. It might also help to increase the font size to highlight certain parts of the page e.g. bolded text.

**Comment by jeanpaulrsoucy** [comment]
This is a great idea, hopefully easily implementable via CSS/HTML.
