### ISSUE TITLE
More vaccine plots

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDashboard#3]
Some additional plots are needed on the vaccine tab.

- [x] Distribution of vaccine doses per-capita (per 100,000 population)
- [x] "Gap tracker": Gap between distribution and administration
- [x] Percent of the population with at least one dose (at the province level)
- [x] Percent of the population fully vaccinated (at the province level)
- [x] Based on the 7-day average of doses administered, how long would it take to get x% of the population vaccinated?
- [x] Daily doses administered (7-day average) on overview plot

**Comment by jeanpaulrsoucy** [comment]
Gap tracker added by 1787d68719effd7065447f107412c7d1640a048c.

**Comment by jeanpaulrsoucy** [comment]
Draft of per-capita/percent fully vaccinated/time to x% vaccination added by @benkcwong in 64c6d52.

**Comment by jeanpaulrsoucy** [comment]
@benkcwong: Good start on the time to % vaccinated table. A few comments.

* When adjusting the percent vaccination from the default (30%), the table headers become left-aligned but the table remains centred. See below.

![vax](https://user-images.githubusercontent.com/31170087/107860473-80d4ec00-6e0d-11eb-9990-7ae2a77c68fd.png)

* The default % vaccination should probably be set to 70% by default.
* Make sure column formatting is consistent (e.g., commas).
* The search bar is unnecessary and can be disabled (see example in overview table).

**Comment by jeanpaulrsoucy** [comment]
@benkcwong: With respect to % fully vaccinated, we should actually be showing % of total population fully vaccinated, rather than % of those who have received at least one dose that are fully vaccinated. This is my fault for providing example code for the latter, as in that context I was making a different point about vaccination strategies (withholding second dose or not).

**Comment by jeanpaulrsoucy** [comment]
@benkcwong: For the per-capita plots, I'm almost wondering if we can roll up this plot with the other cumulative plot and have two options: over time (line graph) versus current (bar graph) and per-capita versus absolute. We could also use unified hover pointed out by @kbelisar to facilitate comparison on the line graphs. I'll give these a think over.

**Comment by benkcwong** [comment]
Updated the percent vaccination table in [`03d16ad`](https://github.com/ccodwg/Covid19CanadaDashboard/commit/03d16ada1ff80dd24f7b13317e94c064b12ee664).
Column/header alignment fixed, column numbers changed to a consistent format, and search bar removed.

Solution to misaligned columns and headers described in: https://stackoverflow.com/questions/46287971/column-headers-of-shiny-data-table-gets-shifted
Misalignment is due to `ScrollX = TRUE` when the table fits within the page width without it.

**Comment by jeanpaulrsoucy** [comment]
Nice job fixing the table bug, @benkcwong. Some additional comments on the table:

* Would it be possible for the column title to read: "Expected date to reach X% fully vaccinated?" Where X is read from the slider.

Can we also add a footnote to the table describing how the expected date is calculated based on the 7-day average of vaccine doses administered per day, assuming everyone receives 2 doses (but not accounting for the delay between doses).

Of course, we might have to tweak this whole table/formula once a 1-dose vaccine gets thrown into the mix, but we'll deal with that issue when it arrives.

**Comment by benkcwong** [comment]
Thanks, updated the column title and footnote in [`1fb8af8`](https://github.com/ccodwg/Covid19CanadaDashboard/commit/1fb8af8cdbc9dd01dfbe8c92cd0a1d8090bab554).

**Comment by jeanpaulrsoucy** [comment]
Looks great, @benkcwong. An issue with the table on mobile is that in (at least in landscape mode), the table is too wide, thus needs to be scrollable horizontally. Could you also freeze the first column, as is the case for the overview table? 

Can you try implementing the alternative to scrollX described here: https://stackoverflow.com/a/64612713

**Comment by benkcwong** [comment]
Sorry I missed this comment, JP! Thanks for these commits. I reviewed them and they look good to me!

**Comment by jeanpaulrsoucy** [comment]
We should also add "daily doses administered" (7-day rolling average) to the overview tab.

**Comment by jeanpaulrsoucy** [comment]
Another calculation that might be useful on vaccines: what percentage of vaccines will be left in the freezer by the time the next delivery comes around, based on the 7-day average pace of administration?

The vaccine dose delivery numbers from PHAC (which we use for *most* provinces) typically get updated on Thursdays, so this makes sense as the window to use [in fact, could explicitly freeze the distribution number at Thursday's value for purposes of calculating this value?].

This could give more context to people talking about the number of vaccines in freezers shortly after more doses are delivered, which is misleading absent context.

**Comment by jeanpaulrsoucy** [comment]
Minor updates to vaccine table (ae9f7ca).

**Comment by andibakti** [comment]
Hey all,

I'm looking at the 'Expected date to reach X%' and it feels more appropriate to model it as a logistic curve rather than a linear one as in here
` date_to_vaxx = max(date_vaccine_administered) + round((total_remaining) / roll_avg, 0),`

(it's also more optimistic and could greatly exceed vaccine supply)

This involves some fitting functions though so this might be out of scope of this issue

**Comment by benkcwong** [comment]
Thanks for the feedback, Andi! Our initial idea was to include a simple calculation to give a quick snapshot of vaccine rollout progress - a logistic curve is definitely a sensible alternative for the reasons you outlined. Will bring this up at our next team meeting and discuss whether it's something to pursue in future updates.

**Comment by benkcwong** [comment]
Added "daily doses administered" (7-day rolling average) to the overview tab as part of the vaxview-update branch ([7789819](https://github.com/ccodwg/Covid19CanadaDashboard/commit/7789819c43ae4d183f657fe9da346f9bd7dcffee)). In hindsight, probably should have called this the overview-tab-update.

**Comment by jeanpaulrsoucy** [comment]
Hi @andibakti. The purpose of this calculation is more to get a sense of how fast we are vaccinating --- i.e., how long it would take to get x% of the population vaccinated at the speed we've been going the past week, with the implicit assumption that supply is not an issue. Happy to consider any alternate formulas if you want to whip up a little chart/calculation as demonstration, though.

**Comment by andibakti** [comment]
I made this as a quick example, these values are for QC only. Green line would be the set x% of population reached
![image](https://user-images.githubusercontent.com/25236329/114625041-a9e3f280-9c7f-11eb-8758-4668d21172b8.png)

Essence of the calculation was this
```
x = np.array(df_total.index) + 1
y = np.array(df_total['vac_cum_tot_n'])

def my_logistic(t, a, growth_rate, saturation_lvl):
  return saturation_lvl /(1 + a * np.exp(-growth_rate*t))

import scipy.optimize as optim
(a, r, K), __ = optim.curve_fit(my_logistic, x, y, bounds=bounds, p0=p0)
```
Though I admit a simple week over week growth of rolling average would illustrate this point

**Comment by benkcwong** [comment]
Added plot for "percent of the population with at least one dose (at the province level)" in the vaccine tab ([6fd5efc](https://github.com/ccodwg/Covid19CanadaDashboard/commit/6fd5efcf0bd98fed880712b3ff5faf4ccba904df)).
