### ISSUE TITLE
Add per-capita toggle to EpiView (and VaxView, where appropriate)

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDashboard#31]
Should this be handled as a Shiny button or as a toggle directly within the plot itself (e.g., a Plotly button)?

**Comment by benkcwong** [comment]
Pushed a basic per-capita toggle for EpiView (cases, deaths, recovered) and VaxView (vax distributed, administered) at [a9cfe49](https://github.com/ccodwg/Covid19CanadaDashboard/commit/a9cfe491d65ff2b73638def57ca3bf52514307ba).
