### ISSUE TITLE
Overview plots: Change in past 7 days

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDashboard#32]
For the overview plots, it should be possible to show the change in the values in the past 7 days (e.g., cases added in the last 7 days, percent of population receiving at least one dose in the last 7 days, etc.).

For slider-enabled plots, this would also mean either limiting the slider to 7 days or modifying the calculating accordingly. The information could either be a toggle button (show change/show total) or additional on hover/click.

**Comment by benkcwong** [comment]
Pushed an update for the 14-day trend plot to the overview page at [407807d](https://github.com/ccodwg/Covid19CanadaDashboard/commit/407807d71762d5d7d0b9be73c306b4bc95752563)
