### ISSUE TITLE
VaxView tooltips should provide more information

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDashboard#4]
Currently, VaxView (on the overview tab) only provides province shortcode: doses administered. It should give more data, as available:

- [x] Doses distributed
- [x] Doses administered as a percentage of doses distributed (doses in freezers versus doses in arms)
- [x] Percent of population fully vaccinated

**Comment by benkcwong** [comment]
Added three VaxView maps to the vaxview-update branch ([bc4373b](https://github.com/ccodwg/Covid19CanadaDashboard/commit/bc4373b128b8310e0fbaa0621175aa3aa305e51a)).
